@host=https://localhost:7095

POST {{host}}/auth/register HTTP/1.1
Content-Type: application/json

{
    "firstName": "test",
    "lastName": "test",
    "username": "name12@",
    "email": "girih14132@letpays.com",
    "password": "test123"
}