#!/usr/bin/bash
 
entity=$1
baseDir="../.."
appDir=$(find "$baseDir" -type d -name "*\.Application")
PersistenceDir=$(find "$baseDir" -type d -name "*\.Persistence")

# touch $entity
touch ${entity}.cs
touch "${appDir}/Common/Interfaces/Persistence//IRepositoriesI${entity}Repository.cs"
touch "${PersistenceDir}/Repositories/${entity}Repository.cs"
touch "${PersistenceDir}/Context/Configurations/${entity}Configuration.cs"