@host=https://localhost:7199

POST  {{host}}/test HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMGVkYWZlMy1iMDQ3LTU5ODAtZDBmYS1kYTEwZjQwMGMxZTUiLCJqdGkiOiJlZjJlZmRmMi1hYTNiLTRmMWEtOGYxMi1lYWQ4NzkzZTdmM2YiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IkFkbWluIiwicm9sZXMiOiJBZG1pbiIsImV4cCI6MTY3NDc1OTA0NiwiaXNzIjoiRGlhZ25vc2VNZUFwaSIsImF1ZCI6IkRpYWdub3NlTWVBcGlVc2VycyJ9.5JjXx01iYoBq5_ez-LtWu2aOWEJ42lzC0_2i4YFc6Nk
Content-Type: application/json

{
}